### ISSUE TITLE
:hover and z-index issue

### ISSUE THREAD

**Issue by matthieudou** [jadjoubran/webdash#36]
Hi, 

First of all, thanks for the awesome job.

It looks that there is a little problem with the dropdowns.
When clicking on a dropdown and hovering another element, the dropdown goes in the "background"

here are some screenshots: 
![capture d ecran 2018-03-26 a 14 41 44](https://user-images.githubusercontent.com/18487606/37907715-32631e26-3106-11e8-8e74-d50e297d6dea.png)
![capture d ecran 2018-03-26 a 14 54 35](https://user-images.githubusercontent.com/18487606/37907716-32ddb3fc-3106-11e8-9a26-9b428603480e.png)

**Comment by jadjoubran** [comment]
Thanks @matthieudou!
The 1st issue is easily fixable
The 2nd one is a bit more complicated, and has been temporarily fixed by making it work only when you hover on the "active" component (the one that has the dropdown)
I'll submit a fix for the 1st issue soon!
