### ISSUE TITLE
[bug] No package.json file

### ISSUE THREAD

**Issue by TheEdgeOfRage** [jadjoubran/webdash#42]
When I try to run `npx webdash serve` I get an error saying that there is no package.json file even though there is one in the current directory. I installed webdash and it's plugins through yarn, as I did with the rest of my packages.

OS: ArchLinux 4.15
npx -v: 9.7.1
node -v: 9.9.0
npm -v: 5.7.1

Please let me know what else you need information wise.

**Comment by jadjoubran** [comment]
Thanks for checking out webdash and reporting the issue 😄 
Did you run it with `--dev` flag rather than `--save-dev`? (because you used yarn)
Also can you please make sure `webdash` and its plugins show up in the `devDependencies` in your package.json?

**Comment by TheEdgeOfRage** [comment]
Okay, I tried doing everything from scratch with --dev and it worked this time, though I was pretty sure I did install it under dev the first time. I might have skipped the on one package ¯\\\_(ツ)_/¯.

Thanks anyway :)

**Comment by jadjoubran** [comment]
Cool! Let me know if you've got feedback on webdash or if you have an idea for a plugin 🚀
