### ISSUE TITLE
npx webdash serve error

### ISSUE THREAD

**Issue by ahmadalibaloch** [jadjoubran/webdash#45]
After installing when I run `npx webdash serve` it gives this in terminal `Object.entries is not a function`

Its a webpack react app directory that I am installing in.

**Comment by jadjoubran** [comment]
Hi @ahmadalibaloch 
Thanks for giving webdash a try!
You're most likely running a node version that is older than `8.0`
Can you please upgrade node and try again?

**Comment by ahmadalibaloch** [comment]
It solved the problem.

**Comment by jadjoubran** [comment]
yeah indeed, that's because it was broken
I'm gonna properly fix this by showing a warning if you run `webdash serve` on an incompatible node version here #46
