### ISSUE TITLE
Not working with MeteorJS

### ISSUE THREAD

**Issue by rolljee** [jadjoubran/webdash#53]
Hello, currently working on a project using MeteorJS

## Step to reproduce

```shell
meteor npm install --save-dev webdash-package-json webdash-npm-scripts webdash-performance-budget webdash-pwa-manifest

npx webdash serve
```

## Output

![screen shot 2018-03-29 at 15 58 08](https://user-images.githubusercontent.com/10114634/38093035-1208b526-336a-11e8-96b3-018c7f4b2783.png)

## In the project

![screen shot 2018-03-29 at 16 03 25](https://user-images.githubusercontent.com/10114634/38093277-bcfb3684-336a-11e8-9044-9ef4c31c33cc.png)

## Bug? Or I am doing something wrong?

**Comment by jadjoubran** [comment]
Thanks for giving webdash a try @rolljee!
Can you please paste here the entires of `webdash` and `webdash-` plugins in your package.json
Also are they in `dependencies` or `devDependencies`?
Also what does `meteor npm install` do differently than simply running `npm install`? (I never used meteor)

**Comment by jasonk** [comment]
All that `meteor npm install` really does is to make sure that you run the version of `npm` that is bundled with meteor rather than the system one.

All that you have to do to make this work is use `meteor npx` too..

```
meteor npm install --save-dev webdash-package-json webdash-npm-scripts webdash-performance-budget webdash-pwa-manifest

meteor npx webdash serve
```

**Comment by rolljee** [comment]
Hello Again! I've made some tests working against Meteor

@jasonk I've tried all these things... neither wrapped or not wrapped with Meteor, the output is the same

@jadjoubran Yes all of them are in the devDepedencies

Other thing, all plugins installed are making meteor to crash and cannot restart with this output

![screen shot 2018-03-30 at 12 13 18](https://user-images.githubusercontent.com/10114634/38134532-dadfec86-3413-11e8-975a-fd463ea65188.png)

**Comment by jadjoubran** [comment]
it's not clear what's "not working"
What command are you running?
The screenshot doesn't seep to be `npx webdash serve` (or `meteor npx webdash serve`)

Please give us more context to be able to help

**Comment by rolljee** [comment]
![screen shot 2018-03-30 at 17 32 56](https://user-images.githubusercontent.com/10114634/38143977-353cb536-3443-11e8-8eef-b7436f549b93.png)


Here is a screenshot of the step to reproduce.

I've made a sample repo to let you test : https://github.com/rolljee/meteor-webdash

**Comment by jadjoubran** [comment]
Thanks for setting up a sample repo! 😄 
I couldn't setup meteor successfully yesterday, the installer kept on failing
I'll give it another try today

**Comment by rolljee** [comment]
Just some steps if you are not familiar with meteor :)

1. curl https://install.meteor.com/ | sh 
1. cd into the cloned repo
1. run meteor nom install ( install all from package.json )
1. you can then follow steps on the last screenshot 👍 


using meteor create command automatically install all dependencies, but when you clone you have to manually do it yourself !

**Comment by jadjoubran** [comment]
Okay I was able to set it up

1. Your package.json (in the example repo) is missing `webdash` from the devDependencies.. you need to install it with `meteor npm install --save-dev webdash` (this is different than the plugins, this is webdash core)

<img width="459" alt="screen shot 2018-03-31 at 2 16 07 pm" src="https://user-images.githubusercontent.com/2265232/38162678-5336ce04-34ee-11e8-8156-1d8b85671e81.png">

2. I was able to make it work
<img width="532" alt="screen shot 2018-03-31 at 2 16 26 pm" src="https://user-images.githubusercontent.com/2265232/38162680-57e849be-34ee-11e8-9fa0-cc6a5c2a5293.png">

<img width="1440" alt="screen shot 2018-03-31 at 2 16 40 pm" src="https://user-images.githubusercontent.com/2265232/38162681-5c4b0c26-34ee-11e8-8c51-65b26474ca9e.png">


Can you please clone the sample repo, and run `meteor npm install --save-dev webdash` and then run `meteor npx webdash serve` and let me know if it works

**Comment by rolljee** [comment]
As simple as that, thank you for your time ! 
Great work ! 
It's perfectly working on chrome !

![screen shot 2018-03-31 at 19 35 34](https://user-images.githubusercontent.com/10114634/38165867-d8097f7e-351a-11e8-87a6-de3006e2f963.png)


however it is acting weird on safari, see the capture below

![screen shot 2018-03-31 at 19 37 40](https://user-images.githubusercontent.com/10114634/38165887-3e6919f0-351b-11e8-81d5-20721d6a65ad.png)


1. Display is overlapping 
1. Package.json plugin are not loaded

When I first log to the page I can see the package.json plugin loading and display something, but then 1 sec later it goes away.

Safari web console show this

![screen shot 2018-03-31 at 19 41 41](https://user-images.githubusercontent.com/10114634/38165907-9809540c-351b-11e8-9f3a-e03bd51490e9.png)

Witch is leading to this piece of code

![screen shot 2018-03-31 at 19 42 26](https://user-images.githubusercontent.com/10114634/38165913-b38d61c8-351b-11e8-968d-9180a3215d54.png)

If you want me to close this issue since the issue is answered and you want me to open an other issue ??

Again, thx again for your time.

**Comment by jadjoubran** [comment]
Awesome, I'm glad that it works!

That's because Safari doesn't support merging objects using the spread operator `...`
It's working for me on Safari Technology Preview, can you please try updating Safari to the latest? (there was an update just yesterday)
and let me know if it works or not
Thanks!

**Comment by rolljee** [comment]
It work with technology Preview 👍
