### ISSUE TITLE
Workbox plugin

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/webdash#55]
Web based configuration wizard for Workbox, originally discussed in [workbox#822](https://github.com/GoogleChrome/workbox/issues/822)

**Comment by jadjoubran** [comment]
Technical analysis:
* webdash-workbox would have workbox as a dev dependency
* you'll be presented with a start wizard button that spawns npx workbox wizard in the end-user's project directory
* the choices that you'd typically see in the console, will be displayed in webdash dashboard, as paper-checkbox or paper-radio-button
* this means we don't lose context about the filesystem since the wizard is running in the end-user directory
* after the workbox-config has been initialized, the plugin will serve as stats for your generated service-worker: for example, latest version of service worker (cache name), version of workbox running, and the ability to re-run the wizard and override the configuration

**Comment by kakadiadarpan** [comment]
@jadjoubran a GUI for workbox would lower the barrier for a lot of people to start using it 😍

**Comment by jadjoubran** [comment]
Indeed! 😄 
I hope to have many webdash plugins that will facilitate building PWAs

**Comment by jadjoubran** [comment]
Developed started 👉[jadjoubran/webdash-workbox](https://github.com/jadjoubran/webdash-workbox)

Here's the workbox-config.js from webdash:

```json
module.exports = {
  "globDirectory": "build/default",
  "globPatterns": [
  "**/*.{html,js,png,xml,ico,svg,json}",
  ],
  "globIgnores": [
  "bower_components/**"
  ],
  "swDest": "build/default/service-worker.js",
  "runtimeCaching": [{
    urlPattern: /bower_components\//,
    handler: 'cacheFirst',
  }]
};
```

The webdash workbox plugin will guess some defaults, especially those available in `webdash.json`
`runtimeCaching` generation won't be supported out of the box (at least not in the first version)
and all of these guesses will be validated by the user

**Comment by jadjoubran** [comment]
Progress:

![gif](https://user-images.githubusercontent.com/2265232/38312307-19009cc6-382a-11e8-9097-c4d8868f2162.gif)

<img width="662" alt="screen shot 2018-04-05 at 2 36 57 pm" src="https://user-images.githubusercontent.com/2265232/38363840-da9434d8-38de-11e8-8990-3eb4db535dc6.png">
<img width="646" alt="screen shot 2018-04-05 at 2 37 01 pm" src="https://user-images.githubusercontent.com/2265232/38363841-dacabc42-38de-11e8-8431-3eeb02f183f7.png">
<img width="640" alt="screen shot 2018-04-05 at 2 37 05 pm" src="https://user-images.githubusercontent.com/2265232/38363842-dc0496be-38de-11e8-8799-7469e34e4ae1.png">

**Comment by jadjoubran** [comment]
- [ ] Patch release with minor fixes
- [ ] Take screenshot
- [ ] Finalize readme.md
- [ ] Record screencast & edit it
- [ ] Add to website
- [ ] Add to Documentation
