### ISSUE TITLE
[webdash-package-json] webdash.json serverScripts

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/webdash#59]
After adding long process support by @bardiarastin [here](https://github.com/jadjoubran/webdash-npm-scripts/pull/8/files)
We need to add `serverScripts` to `webdash.json` config
This one doesn't need smart guessing, we can simply default to typical server commands such as:
* dev
* start
* serve
* server
* watch

in [config-helper](https://github.com/jadjoubran/webdash/blob/master/scripts/lib/config-helper.js#L82)

**Comment by bardiarastin** [comment]
pull request #60 is here for this
