### ISSUE TITLE
Make an option to not update package.json

### ISSUE THREAD

**Issue by Neoares** [jadjoubran/webdash#76]
It would be nice to allow package upgrading without modifying the package.json semver.

For instance, if I have "^1.2.0" and I upgrade to "1.3.4", the package.json semver would remain as "^1.2.0".

This could be included in a future options tab/panel, and it would basically run `npm install` without `--save` flag.

**Comment by jadjoubran** [comment]
Thanks @Neoares 
I thought this is already how it works.. no?
Checkout this issue [Doesn't update package.json file](https://github.com/jadjoubran/webdash-package-json/issues/9)

**Comment by jadjoubran** [comment]
Afaik, as of `npm` 5 `--save` is automatically inferred

**Comment by Neoares** [comment]
Fine, didn't really know about that inferring.
