### ISSUE TITLE
Add a --no-open flag

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/webdash#87]
This flag will not run `opn(url)`

**Comment by felipenmoura** [comment]
Was this added? I created a script called "dash" that executes `webdash --port 8089 --no-open`
But when I run "npm run dash" it always opens the window :/
Also, it is not using the webdash.json configuration.
Any idea what I may be doing wrong?

**Comment by jadjoubran** [comment]
Hey @felipenmoura 
This hasn't been published yet as a stable release but you can already grab it with `npm install webdash@next`
Let me know if it works for you!

**Comment by jadjoubran** [comment]
Hey @felipenmoura 
This is not in stable `v1.5.0`
