### ISSUE TITLE
The use of Google trackers

### ISSUE THREAD

**Issue by theAlchemist-dev** [jadjoubran/webdash#88]
Hey,

I really like Webdash, but I do not think using Google Analytics and/or Tag Manager on my local environment should be enabled.

Is there a way to disable these trackers from the configuration json?

Best regards

**Comment by jadjoubran** [comment]
Hey @theAlchemist-dev 
Thanks for opening this issue
Indeed, they shouldn't be there
I had them in the beginning to understand the majority of users using webdash
I will issue a commit tonight removing them and them issue a new patch release

**Comment by jadjoubran** [comment]
@theAlchemist-dev done!
it will be officially released with 1.5 but you can grab it already by installing `webdash@next`
Thanks again and I'm glad you're enjoying webdash
I'd love it if you can contribute or even suggest new features
Cheers!

**Comment by theAlchemist-dev** [comment]
Thanks, 

I understand completely.
Thank you for the quick resolve :)

**Comment by jadjoubran** [comment]
Hey @theAlchemist-dev 
This is now in stable `v1.5.0`
a regular npm install should work
